### ISSUE TITLE
Bug: [BUG]Could not find file appsettings.json

### ISSUE THREAD

**Issue by echoenzo** [ICTOOSDDd4/OpenPOS#121]
I clone the master ,and try build the project
build error!! 
so what can i do?
error code:
CSC : error CS1566: 读取资源“OpenPOS_APP.appsettings.json”时出错 --“Could not find file 'C:\Users\enzo\Downloads\OpenPOS-master\OpenPOS-APP\appsettings.json'.” [C:\Users\enz
o\Downloads\OpenPOS-master\OpenPOS-APP\OpenPOS-APP.csproj::TargetFramework=net7.0]
CSC : error CS1566: 读取资源“OpenPOS_APP.appsettings.json”时出错 --“Could not find file 'C:\Users\enzo\Downloads\OpenPOS-master\OpenPOS-APP\appsettings.json'.” [C:\Users\enz
o\Downloads\OpenPOS-master\OpenPOS-APP\OpenPOS-APP.csproj::TargetFramework=net7.0-maccatalyst]
CSC : error CS1566: 读取资源“OpenPOS_APP.appsettings.json”时出错 --“Could not find file 'C:\Users\enzo\Downloads\OpenPOS-master\OpenPOS-APP\appsettings.json'.” [C:\Users\enz
o\Downloads\OpenPOS-master\OpenPOS-APP\OpenPOS-APP.csproj::TargetFramework=net7.0-windows10.0.19041.0]

**Comment by Tymen** [comment]
Please look at the appsettings.dev.json. You can rename this to appsettings.json and fill in any necessary data

**Comment by echoenzo** [comment]
> Please look at the appsettings.dev.json. You can rename this to appsettings.json and fill in any necessary data

I do that  but someting error is coming! so follow the guid do not runing

**Comment by echoenzo** [comment]
would you re-write the guide and submit a release?please
